[package]
name = "lingioia"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
ron = "0.8"
regex = "1.3.9"
indexmap  = { version = "2", features = ["serde"] }
